name: lowkey
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  equatable: ^2.0.7
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_webrtc: ^0.14.2
  hive: ^2.2.3
  local_auth: ^2.3.0
  rive: ^0.13.20
  sodium_libs: ^3.4.5+2
  supabase_flutter: ^2.9.1
  provider: ^6.0.5
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
